### ISSUE TITLE
Tensorflow installation does not keep showing the loading spinner 

### ISSUE THREAD

**Issue by jps327** [cxl-garage/desktop-app-sentinel#90]
In a production install on a Windows computer:
1. Uninstall tensorflow from your Docker Desktop (if installed)
2. Open the app
3. When it says that tensorflow is not installed, click "Install"
4. The install button should change to a spinner but then change back to an "Install" button even though the installation is still happening behind the scenes!

Unsure if this happens locally on Windows - we haven't tested. This has only been tested on Windows production (i.e. when the app is fully packaged). Also unsure if this happens on Mac as well - that's worth testing too (both locally and in production).

What we'd want is that after clicking "Install" the loading spinner should remain visible until Tensorflow is fully installed.

**Comment by tstmonger** [comment]
Closed by https://github.com/cxl-garage/desktop-app-sentinel/pull/101
